version: "2"

services:
  dev:
    image: hseeberger/scala-sbt:8u212_1.2.8_2.13.0
    working_dir: /work
    command: sbt
    volumes:
      - .:/work
      - ivy-cache:/root/.ivy2
      - docker-scala-sbt-cache:/root/.sbt

volumes:
  ivy-cache:
    external: true
  docker-scala-sbt-cache:
    external: true
