version: "2"

services:
  dev:
    image: sbtscala/scala-sbt:eclipse-temurin-focal-17.0.5_8_1.9.4_3.3.0
    working_dir: /work
    command: sbt
    volumes:
      - .:/work
      - coursier-cache:/root/.cache/coursier
      - docker-scala-sbt-cache:/root/.sbt

volumes:
  coursier-cache:
    external: true
  docker-scala-sbt-cache:
    external: true
